app:
  id: ldbz-shop-service-portal
apollo:
  meta: http://192.168.136.133:8080
  

spring:
  dubbo:
    server: true
  datasource:
    druid:
      filter:
        config:
          enabled: true
          
logging:
  level:
     cn.ldbz.mapper: debug